import { GithubRegistry } from '@hyperlane-xyz/registry';
import type { IRegistry } from '@hyperlane-xyz/registry';
import type { ChainMap, ChainMetadata } from '@hyperlane-xyz/sdk';

const TC_REGISTRY_URL = 'https://github.com/terra-classic-hyperlane/hyperlane-registry';
const TC_REGISTRY_BRANCH = 'main';

// Chains present in individual files but missing from the combined chains/metadata.yaml.
// The combined file is auto-generated by the registry tooling — until it's regenerated to
// include these chains, we fetch them individually and merge them in.
const TC_EXTRA_CHAINS = ['terraclassic', 'terraclassictestnet'];

export class TcRegistry extends GithubRegistry {
  constructor() {
    super({ uri: TC_REGISTRY_URL, branch: TC_REGISTRY_BRANCH });
  }

  override async getMetadata(): Promise<ChainMap<ChainMetadata>> {
    const metadata = await super.getMetadata();
    const missing = TC_EXTRA_CHAINS.filter((c) => !metadata[c]);
    if (!missing.length) return metadata;

    const fetched = await Promise.all(missing.map((c) => this.getChainMetadata(c)));
    const extra: ChainMap<ChainMetadata> = {};
    fetched.forEach((m, i) => {
      if (m) extra[missing[i]] = m;
    });
    return { ...metadata, ...extra };
  }
}

export function createTcRegistry(): IRegistry {
  return new TcRegistry();
}

export { TC_REGISTRY_URL, TC_REGISTRY_BRANCH };
